/**
 * AST → HTML Transformation
 *
 * Converts the Markdown AST generated by remark-parse
 * into safe HTML structure.
 */

// Escape HTML special characters
function escapeHtml(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

// Transform inline/text nodes
function transformText(node) {
  if (!node) {
    return "";
  }

  switch (node.type) {
    case "text":
      return escapeHtml(node.value || "");

    case "inlineCode":
      return `<code>${escapeHtml(node.value || "")}</code>`;

    case "emphasis":
      return `<em>${transformChildren(node)}</em>`;

    case "strong":
      return `<strong>${transformChildren(node)}</strong>`;

    case "delete":
      return `<del>${transformChildren(node)}</del>`;

    default:
      return transformChildren(node);
  }
}

// Transform child nodes
function transformChildren(node) {
  if (!node || !Array.isArray(node.children)) {
    return "";
  }

  return node.children
    .map(transformNode)
    .join("");
}

// Transform one AST node
function transformNode(node) {
  if (!node || !node.type) {
    return "";
  }

  switch (node.type) {
    case "root":
      return transformChildren(node);

    case "heading": {
      const depth = Number(node.depth);

      if (depth < 1 || depth > 6) {
        return "";
      }

      return `<h${depth}>${transformChildren(node)}</h${depth}>`;
    }

    case "paragraph":
      return `<p>${transformChildren(node)}</p>`;

    case "list": {
      const tag = node.ordered ? "ol" : "ul";

      return `<${tag}>${transformChildren(node)}</${tag}>`;
    }

    case "listItem":
      return `<li>${transformChildren(node)}</li>`;

    case "code": {
      const language = node.lang
        ? ` class="language-${escapeHtml(node.lang)}"`
        : "";

      return `<pre><code${language}>${escapeHtml(
        node.value || ""
      )}</code></pre>`;
    }

    case "blockquote":
      return `<blockquote>${transformChildren(node)}</blockquote>`;

    case "thematicBreak":
      return "<hr>";

    case "break":
      return "<br>";

    case "text":
      return escapeHtml(node.value || "");

    case "inlineCode":
      return `<code>${escapeHtml(node.value || "")}</code>`;

    case "emphasis":
      return `<em>${transformChildren(node)}</em>`;

    case "strong":
      return `<strong>${transformChildren(node)}</strong>`;

    case "delete":
      return `<del>${transformChildren(node)}</del>`;

    default:
      // Unsupported nodes are ignored safely
      return "";
  }
}

// Main transformation function
function astToHtml(ast) {
  if (!ast || typeof ast !== "object") {
    throw new TypeError("Invalid AST: expected an object");
  }

  if (ast.type !== "root") {
    throw new TypeError("Invalid AST: root node expected");
  }

  return transformNode(ast);
}

module.exports = {
  astToHtml,
  transformNode,
  escapeHtml
};